#!/usr/bin/env python3
"""This module contains a coroutine that collects 10 random
numbers using async comprehension"""


from typing import List
async_generator = __import__("0-async_generator").async_generator


async def async_comprehension() -> List[float]:
    """Collects 10 random float numbers generated by
    async_generator and returns the float numbers in a List"""
    return [num async for num in async_generator()]
